# Generated by Django 6.0.1 on 2026-01-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='resturant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('MX', 'Mexican'), ('FF', 'Fast Food'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
