# Generated by Django 5.2 on 2026-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggss', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
