# Generated by Django 5.2 on 2026-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggss', '0003_blog_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='drafted', max_length=30),
        ),
    ]
