# Generated by Django 5.2 on 2026-01-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
    ]
