# Generated by Django 6.0.1 on 2026-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.CharField(default='Unknown Restaurant', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
