# Generated by Django 5.2 on 2026-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('discord', 'Discord')], max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Follow Us',
                'verbose_name_plural': 'Follow Us',
            },
        ),
    ]
